---
# tasks file for beats

- name: check-parameters
  include_tasks: beats-param-check.yml

- name: define beat product
  set_fact:
    beat_product: "{{ beat }}"

- name: os-specific vars
  include_vars: '{{ ansible_os_family }}.yml'

- include_tasks: beats.yml

- name: include beats-security.yml
  include: beats-security.yml
  run_once: True

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
